# Generated by Django 4.2.3 on 2023-08-10 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geekuser',
            old_name='frist_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='geekuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
    ]
